### ISSUE TITLE
Pypi

### ISSUE THREAD

**Issue by drgarcia1986** [loisaidasam/pyslack#19]
I'm using pyslack in production (BTW great job, congrats :clap: ) and I think the best way to version control is pypi.

Could you upload pyslack to pypi?

**Comment by RomuloOliveira** [comment]
:+1:

**Comment by renanivo** [comment]
:+1:

**Comment by hery** [comment]
:+1:

**Comment by loisaidasam** [comment]
Voila!

    pip install pyslack-real

Thanks for your patience :+1:

**Comment by drgarcia1986** [comment]
Wow, thank you bro :+1:
